### ISSUE TITLE
Pull out chat client code

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym-mixnet#50]
Remove chat-related functionality from nym-mixnet `client` repo and put it in the new `demo-mixnet-chat-client` repo.

**Comment by jstuczyn** [comment]
Done in https://github.com/nymtech/nym-mixnet/commit/f8c089e66f47f8357952edf7302833b9ac7a1569 and https://github.com/nymtech/demo-mixnet-chat-client/commit/e79b2c0339ad51b6e3808511164df8397e5bc78d
